apiVersion: v1
kind: Service
metadata:
  namespace: awayteam
  labels:
    service: chat
  name: chat
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    service: chat
status:
  loadBalancer: {}