apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: awayteam
  labels:
    service: client
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: client
    spec:
      containers:
        - image: {{ .Values.repository }}/app-client
          name: client
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
