apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: awayteam
  labels:
    service: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
          env:
            - name: discovery.type
              value: single-node
          name: elasticsearch
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: {}
      restartPolicy: Always
status: {}
