apiVersion: v1
kind: Service
metadata:
  namespace: awayteam
  labels:
    service: feature
  name: feature
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: feature
status:
  loadBalancer: {}