apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: grafana
  name: grafana
  namespace: awayteam
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: grafana
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
