apiVersion: v1
kind: Service
metadata:
  labels:
    service: grafana
  name: grafana
  namespace: awayteam
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: grafana
status:
  loadBalancer: {}
