apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: awayteam
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
status: {}
