apiVersion: v1
kind: Service
metadata:
  namespace: awayteam
  labels:
    service: postgres
    dedicated: main
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
status:
  loadBalancer: {}
