apiVersion: v1
kind: Service
metadata:
  namespace: awayteam
  labels:
    service: unleash
  name: unleash
spec:
  ports:
    - name: "4242"
      port: 4242
      targetPort: 4242
  selector:
    service: unleash
status:
  loadBalancer: {}
